# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18b4e5bad4b4e50783e7dbc2c6ba261a8d8c3cc1e4dd8efdaff09754b312b02c9d88f2359f0c074f37c41e294aac37ff4f54a804758f0f773735bde735450785

test:
  secret_key_base: fd2b94c96ef9f6bb8d0e033d5a58bd2de5036a9b1a2ab3915f4c8580b5d7267f0be7aa89e28f4d35ad1dfe208108eaa9fc55e951a2d05434142ea6cef8e3f44c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
